function export(obj,filepath,varargin)
%EXPORT Summary of this function goes here
%   Detailed explanation goes here

varNames = { ...
    'Time', ...
    'Red', ...
    'Green', ...
    'Blue', ...
    'Illuminance', ...
    'CircadianLight',...
    'CircadianStimulus',...
    'ActivityIndex', ...
    'Resets'};

t = table( ...
    datestr(obj.Time,'yyyy-mm-dd HH:MM:SS'), ...
    round(obj.Red*1000)/1000, ...
    round(obj.Green*1000)/1000, ...
    round(obj.Blue*1000)/1000, ...
    round(obj.Illuminance*10)/10, ...
    round(obj.CircadianLight*10)/10, ...
    round(obj.CircadianStimulus*10000)/10000, ...
    round(obj.ActivityIndex*10000)/10000, ...
    obj.Resets, ...
    'VariableNames',varNames);

switch nargin
    case 2
        writetable(t,filepath);
    case 3
        writetable(t,filepath,'Sheet',varargin{1});
    case 4
        if varargin{2}
            t.Compliance = obj.Compliance;
            t = t(obj.Observation,:);
            writetable(t,filepath,'Sheet',varargin{1});
        end
    otherwise
        writetable(t,filepath);
end

end

